<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MvsAnalyzer.Core</AssemblyName>
    <RootNamespace>MvsAnalyzer</RootNamespace>
    <Version>1.4.0</Version>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <Import Project="../SharedSources.props" />
  <ItemGroup>
    <Compile Include="AssemblyInfo.cs" />
  </ItemGroup>
</Project>
